### ISSUE TITLE
Where is the PoW code?

### ISSUE THREAD

**Issue by AugustoResende** [brainblocks/RaiWalletV2#11]

**Comment by jaimehgb** [comment]
Client or server side?
https://github.com/jaimehgb/RaiBlocksWebAssemblyPoW
https://github.com/numtel/nano-webgl-pow

**Comment by AugustoResende** [comment]
Server side

**Comment by jaimehgb** [comment]
Not published, but it's basically a daemon which pulls pow requests from the database, solves them, and then updates them.

**Comment by lephleg** [comment]
@jaimehgb is there a security issue for the PoW code to be private?

**Comment by sarmadmakhdoom** [comment]
I am also looking for server side implementation for PoW, currently the website is sending block hashes but I don't have server side daemon that solves those blocks for the web. Can you please share that code?

**Comment by numtel** [comment]
@sarmadmakhdoom For node.js proof or work: https://github.com/numtel/node-raiblocks-pow

**Comment by sarmadmakhdoom** [comment]
Thank you for the code, can you please guide me how to make that daemon myself? Like with the node library I can calculate the PoW for any hash that needed work in the data. I take the pending hash from database, calculate the work and update the database with the work value. What else needed? How I need to inform the connected node or there is any API on the wallet which I need to call for after hash work solving. All of you help will be appreciated. 

Thanks

**Comment by sarmadmakhdoom** [comment]
After doing some testing, the web wallet automatically continue broadcasting the block once work has been updated to the database. It worked like a charm. Loved the whole work
