### ISSUE TITLE
Not working with localhost

### ISSUE THREAD

**Issue by apasov** [brainblocks/RaiWalletV2#13]
On my server it started working only after I changed default host for rai_node requests from localhost to [::1]
https://github.com/jaimehgb/RaiWalletV2/blob/9eb3ef6a68bae780f760d10e7c395617242c87be/app/Custom/RaiNode.php#L101
I think there must be an option in .env for default rai_node requests host.

**Comment by jaimehgb** [comment]
True, that'd make sense. It works on mine as I have localhost mapped to ::1 too, but definitely a good thing to have.

BTW, check if this (https://github.com/jaimehgb/RaiWalletV2/pull/12) is still happening after setting up rai_node correctly. I've got 500 codes with the node being offline, but not when not having pending blocks.
