### ISSUE TITLE
RaiwalletV2 Build

### ISSUE THREAD

**Issue by VinickGold** [brainblocks/RaiWalletV2#6]
Hi, i'm trying to build the project following the instructions. I have installed "Wamp Server", then i installed "Composer", then node version 6.10.3 cause the latest version of node (9.5.0) is not compatible with some project dependencies. 

After that i run the commands in the project repository README. The site is being served on my localhost:8000. After that i created an account/wallet and the keys are set in the database. But when i try to log in with the recently created wallet. The app stuck in the loading screen due an unexpected null value, in the wallet balance (I suppose the javascript is expecting an SmallInteger instead of null). There is something i'm doing wrong? Is it a know issue? Which version of node are you using to restore the project dependencies? If i can provide more information, let me know.

![image](https://user-images.githubusercontent.com/8043172/36513682-8c84920c-174f-11e8-8267-c1818d62d7c1.png)

Thanks in advance :)

**Comment by jaimehgb** [comment]
Interesting. I'll check the dependencies issues on v9.5.0.
I've tested it and works on 8.9.3 and 8.9.4.

**Comment by VinickGold** [comment]
I tried to to restore the dependencies with node node v8.9.4 this morning before go to work, but the dependency restore fails with the same error when i used the v9.5.0. Seens something related to node-sass/gyp dependencies.

![error restoring dependencies npm 8 9 4](https://user-images.githubusercontent.com/8043172/36591588-3d511f98-1871-11e8-8c73-9b09f4d9321a.png)

I will try to install python2 as suggested in this stackoverflow and check if it works:
https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp

**Comment by VinickGold** [comment]
After little time searching i found there are some dependencies not specifiend on the build instructions if you want to run the project with node version 6.++ on windows (I can provide detailed instructions later if needed ). Now i can build the project using node 8.9.4. But this is not the root cause of the original error, when i get a null reference exception when try to login after build and execute the project.

**Comment by VinickGold** [comment]
Hi @jaimehgb , related to the node version issue. The node node-sass package has a dependency on gyp, and gyp has a dependency on Python2 e Visual C++ compliler. Basically to solve this dependency you need to execute the command "npm install --global --production windows-build-tools" before restore the project dependencies with node v6++. I think would be nice add this information in the build instructions for windows users. 

[Link for Reference](https://www.npmjs.com/package/node-gypurl)

**Comment by VinickGold** [comment]
After install the XDebug i finally found why i'm getting null reference exception when trying to log in the app. Basically the call to Rainode on walletscontroller is failling (return false as class documentation says) and the error is not being catch (i think is because the Rainode is pointing to localhost:7076). Where should i point the Rainode in a development enviroment in order to get a sucessfull response? There is some configuration i need to do before run the app? Thanks in advance.

**Comment by apasov** [comment]
The same on node 9.7.1
To fix this error a dependency code must be changed: https://github.com/chriscohoat/rai-wallet
I submitted a pull request https://github.com/chriscohoat/rai-wallet/pull/11
